version: '3.1'

services:

  web:
    image: nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${SSL_DOMAINS}
      LETSENCRYPT_EMAIL: ${SSL_EMAIL}
    volumes:
      - ./dist:/usr/share/nginx/html

networks:
    default:
       external:
         name: ${NETWORK}
